'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';
import { SupportedLanguage } from '@/types';

export interface LanguageOption {
  code: SupportedLanguage;
  label: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English (Global)', flag: '🌐' },
  { code: 'hi', label: 'हिन्दी (India)', flag: '🇮🇳' },
  { code: 'pt', label: 'Português (Brasil)', flag: '🇧🇷' },
  { code: 'ru', label: 'Русский (Россия)', flag: '🇷🇺' },
  { code: 'zh', label: '中文 (中国)', flag: '🇨🇳' },
  { code: 'ar', label: 'العربية (مصر/الإمارات)', flag: '🇪🇬' },
  { code: 'sw', label: 'Kiswahili (East Africa)', flag: '🇪🇹' },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Nav
    'nav.overview': 'Overview',
    'nav.citizen': 'Citizen Voice',
    'nav.operations': 'Operations',
    'nav.planning': 'Policy Intelligence',
    'nav.impact': 'Impact Registry',
    'nav.governance': 'Governance & Ethics',
    'nav.sign_in': 'Sign In',
    'nav.sign_out': 'Sign Out',
    'header.subtitle': 'AI for Digital Public Infrastructure & Governance',
    'header.dpg_badge': 'DPG v1.0',

    // Hero
    'hero.track_badge': 'BRICS Track 1 — AI for Digital Public Infrastructure & Governance',
    'hero.title_part1': 'Bridging Citizen Need with',
    'hero.title_highlight': 'National Infrastructure Priorities',
    'hero.subtitle': 'A scalable, multilingual AI platform designed as a Digital Public Good — aggregating citizen development requests via voice, text, and messaging to surface demand hotspots, eliminate spending gaps, and recommend high-priority infrastructure projects to national policymakers across BRICS nations.',
    'hero.search_placeholder': 'Search demand hotspots, pincodes (424001, 0152), water, clinic...',
    'hero.voice_report_btn': 'Voice Report',
    'hero.direct_filters': 'Direct Filters:',

    // KPIs
    'kpi.requests_num': '1,280+',
    'kpi.requests_label': 'CITIZEN REQUESTS',
    'kpi.hotspots_num': '48',
    'kpi.hotspots_label': 'DEMAND HOTSPOTS',
    'kpi.triage_sla_num': '< 4 Hours',
    'kpi.triage_sla_label': 'AI TRIAGE & ROUTING',
    'kpi.spending_num': '$3.55M',
    'kpi.spending_label': 'ALIGNED SPENDING',

    // Ticker
    'ticker.verified_deliveries': 'Verified Deliveries',
    'ticker.view_registry': 'View Registry',

    // Pipeline
    'pipeline.badge': 'End-to-End Decision Support System',
    'pipeline.title': 'From Spoken Feedback to Defensible Public Spending',
    'pipeline.subtitle': 'Bridging fragmented municipal systems through transparent multi-criteria policy intelligence.',
    'pipeline.step1_title': 'Multilingual Intake',
    'pipeline.step1_desc': 'Captures voice notes, text, WhatsApp bots, and 2G USSD across 7 pilot BRICS languages with auto GPS & Pincode.',
    'pipeline.step2_title': 'Resilient AI Gateway',
    'pipeline.step2_desc': 'Extracts domain, urgency, and affected population with cascading failover across Gemini, Groq, and Local NLP.',
    'pipeline.step3_title': 'Geospatial Hotspots',
    'pipeline.step3_desc': 'Combines citizen demands with national census data, infrastructure indices, and 300m spatial clustering buffers.',
    'pipeline.step4_title': 'Policy Recommendations',
    'pipeline.step4_desc': 'Ranks high-priority development projects using 6-factor composite scoring and tracks closed-loop delivery.',

    // Sandbox
    'sandbox.badge': 'Live Interactive Sandbox',
    'sandbox.title': 'Test Multilingual Voice & AI Intent Extraction',
    'sandbox.subtitle': 'Experience how messy spoken dialect is automatically structured into domain, urgency, and pincode location in real time.',
    'sandbox.full_portal_btn': 'Full Citizen Problem Portal',

    // Live Demands
    'demands.badge': 'Live Demand Hotspots',
    'demands.title': 'Recently Reported Community Infrastructure Deficits',
    'demands.view_all_btn': 'View All Problems & Submit Yours',

    // Map
    'map.badge': 'Spatial Decision Support',
    'map.title': 'BRICS Territory Demand Hotspots & Deficit Mapping',
    'map.subtitle': 'Surfacing geographic demand concentrations and unaddressed infrastructure gaps across South Africa, India, Brazil, Russia, China, Egypt, and Ethiopia.',
    'map.launch_btn': 'Launch Policy Prioritization Workspace',

    // Footer
    'footer.dpg_header': 'BRICS Track 1 — AI for Digital Public Infrastructure & Governance',
    'footer.dpg_desc': 'An open-source Digital Public Good (DPG) aligning grassroots citizen voice with national capital budgets.',
    'footer.member_nations': 'MEMBER NATIONS PILOT DEPLOYMENT',
    'footer.product_surfaces': 'Product Surfaces',
    'footer.privacy_governance': 'Privacy & Governance',
    'footer.municipal_access': 'Municipal Access',
    'footer.official_login': 'Official Governance Sign-In',
  },
  hi: {
    // Nav
    'nav.overview': 'अवलोकन',
    'nav.citizen': 'नागरिक आवाज़',
    'nav.operations': 'संचालन डेस्क',
    'nav.planning': 'नीति इंटेलिजेंस',
    'nav.impact': 'प्रभाव रजिस्ट्री',
    'nav.governance': 'शासन और नैतिकता',
    'nav.sign_in': 'साइन इन',
    'nav.sign_out': 'साइन आउट',
    'header.subtitle': 'डिजिटल पब्लिक इंफ्रास्ट्रक्चर और शासन हेतु AI',
    'header.dpg_badge': 'DPG v1.0',

    // Hero
    'hero.track_badge': 'ब्रिक्स ट्रैक 1 — डिजिटल पब्लिक इंफ्रास्ट्रक्चर और शासन हेतु AI',
    'hero.title_part1': 'नागरिक आवश्यकताओं को जोड़ना',
    'hero.title_highlight': 'राष्ट्रीय अवसंरचना प्राथमिकताओं से',
    'hero.subtitle': 'डिजिटल पब्लिक गुड (DPG) के रूप में डिज़ाइन किया गया बहुभाषी AI प्लेटफ़ॉर्म — जो आवाज़, टेक्स्ट और मैसेजिंग के ज़रिए नागरिक विकास अनुरोधों को एकत्रित करता है, मांग हॉटस्पॉट चिन्हित करता है और ब्रिक्स देशों में उच्च प्राथमिकता वाली बुनियादी ढांचा परियोजनाओं की सिफारिश करता है।',
    'hero.search_placeholder': 'मांग हॉटस्पॉट, पिनकोड (424001, 0152), पानी, क्लिनिक खोजें...',
    'hero.voice_report_btn': 'आवाज़ में रिपोर्ट करें',
    'hero.direct_filters': 'सीधे फ़िल्टर:',

    // KPIs
    'kpi.requests_num': '1,280+',
    'kpi.requests_label': 'नागरिक शिकायतें',
    'kpi.hotspots_num': '48',
    'kpi.hotspots_label': 'मांग हॉटस्पॉट',
    'kpi.triage_sla_num': '< 4 घंटे',
    'kpi.triage_sla_label': 'AI ट्राइएज और रूटिंग',
    'kpi.spending_num': '$3.55M',
    'kpi.spending_label': 'स्वीकृत सार्वजनिक खर्च',

    // Ticker
    'ticker.verified_deliveries': 'सत्यापित समाधान',
    'ticker.view_registry': 'रजिस्ट्री देखें',

    // Pipeline
    'pipeline.badge': 'एंड-टू-एंड निर्णय समर्थन प्रणाली',
    'pipeline.title': 'नागरिक आवाज़ से साक्ष्य-आधारित सार्वजनिक बजट तक',
    'pipeline.subtitle': 'पारदर्शी बहु-मानदंड नीति बुद्धिमत्ता के माध्यम से खंडित नगरपालिका प्रणालियों को जोड़ना।',
    'pipeline.step1_title': 'बहुभाषी इनटेक',
    'pipeline.step1_desc': 'ऑटो जीपीएस और पिनकोड के साथ 7 ब्रिक्स भाषाओं में वॉयस नोट्स, टेक्स्ट और व्हाट्सएप संदेश कैप्चर करता है।',
    'pipeline.step2_title': 'लचीला AI गेटवे',
    'pipeline.step2_desc': 'जेमिनी, ग्रोक और स्थानीय एनएलपी में सुरक्षित कैस्केडिंग के साथ डोमेन, तात्कालिकता और प्रभावित जनसंख्या निकालता है।',
    'pipeline.step3_title': 'भू-स्थानिक हॉटस्पॉट',
    'pipeline.step3_desc': '300 मीटर स्थानिक गोपनीयता बफर के साथ राष्ट्रीय जनगणना डेटा और बुनियादी ढांचा सूचकांकों को जोड़ता है।',
    'pipeline.step4_title': 'नीतिगत सिफारिशें',
    'pipeline.step4_desc': '6-कारक समग्र स्कोरिंग का उपयोग करके उच्च प्राथमिकता वाली विकास परियोजनाओं को रैंक करता है।',

    // Sandbox
    'sandbox.badge': 'लाइव इंटरएक्टिव सैंडबॉक्स',
    'sandbox.title': 'बहुभाषी वॉयस और AI वर्गीकरण का परीक्षण करें',
    'sandbox.subtitle': 'अनुभव करें कि कैसे बोली जाने वाली स्थानीय भाषा को वास्तविक समय में डोमेन, तात्कालिकता और पिनकोड में संरचित किया जाता है।',
    'sandbox.full_portal_btn': 'नागरिक समस्या पोर्टल खोलें',

    // Live Demands
    'demands.badge': 'लाइव मांग हॉटस्पॉट',
    'demands.title': 'हाल ही में दर्ज की गई सामुदायिक अवसंरचना समस्याएं',
    'demands.view_all_btn': 'सभी समस्याएं देखें और अपनी दर्ज करें',

    // Map
    'map.badge': 'स्थानिक निर्णय समर्थन',
    'map.title': 'ब्रिक्स क्षेत्र मांग हॉटस्पॉट और कमी मानचित्रण',
    'map.subtitle': 'दक्षिण अफ्रीका, भारत, ब्राजील, रूस, चीन, मिस्र और इथियोपिया में मांग सांद्रता और बुनियादी ढांचा अंतराल का निरीक्षण करें।',
    'map.launch_btn': 'नीति प्राथमिकता कार्यक्षेत्र खोलें',

    // Footer
    'footer.dpg_header': 'ब्रिक्स ट्रैक 1 — डिजिटल पब्लिक इंफ्रास्ट्रक्चर और शासन हेतु AI',
    'footer.dpg_desc': 'नागरिक आवाज़ को राष्ट्रीय पूंजी बजट के साथ संरेखित करने वाला ओपन-सोर्स डिजिटल पब्लिक गुड (DPG)।',
    'footer.member_nations': 'सदस्य राष्ट्र पायलट परिनियोजन',
    'footer.product_surfaces': 'उत्पाद मॉड्यूल',
    'footer.privacy_governance': 'गोपनीयता और शासन',
    'footer.municipal_access': 'नगरपालिका पहुंच',
    'footer.official_login': 'आधिकारिक शासन साइन-इन',
  },
  pt: {
    'nav.overview': 'Visão Geral',
    'nav.citizen': 'Voz do Cidadão',
    'nav.operations': 'Mesa de Operações',
    'nav.planning': 'Inteligência Política',
    'nav.impact': 'Registro de Impacto',
    'nav.governance': 'Governança e Ética',
    'nav.sign_in': 'Entrar',
    'nav.sign_out': 'Sair',
    'header.subtitle': 'IA para Infraestrutura Pública Digital e Governança',
    'header.dpg_badge': 'DPG v1.0',
    'hero.track_badge': 'Trilha 1 BRICS — IA para Infraestrutura Pública Digital',
    'hero.title_part1': 'Conectando a Necessidade do Cidadão às',
    'hero.title_highlight': 'Prioridades Nacionais de Infraestrutura',
    'hero.subtitle': 'Uma plataforma escalável de IA multilíngue projetada como Bem Público Digital — agregando solicitações de cidadãos por voz, texto e mensagens para mapear pontos críticos e recomendar projetos prioritários.',
    'hero.search_placeholder': 'Buscar pontos críticos, CEP (50000), água, saúde...',
    'hero.voice_report_btn': 'Relato por Voz',
    'hero.direct_filters': 'Filtros Diretos:',
    'kpi.requests_num': '1.280+',
    'kpi.requests_label': 'SOLICITAÇÕES DE CIDADÃOS',
    'kpi.hotspots_num': '48',
    'kpi.hotspots_label': 'PONTOS CRÍTICOS DE DEMANDA',
    'kpi.triage_sla_num': '< 4 Horas',
    'kpi.triage_sla_label': 'TRIAGEM E ROTEAMENTO IA',
    'kpi.spending_num': '$3.55M',
    'kpi.spending_label': 'INVESTIMENTO ALINHADO',
    'ticker.verified_deliveries': 'Entregas Verificadas',
    'ticker.view_registry': 'Ver Registro',
    'pipeline.badge': 'Sistema de Suporte à Decisão',
    'pipeline.title': 'Do Relato Falado ao Gasto Público Defensável',
    'pipeline.subtitle': 'Integrando sistemas municipais fragmentados através de inteligência política transparente.',
    'pipeline.step1_title': 'Coleta Multilíngue',
    'pipeline.step1_desc': 'Captura notas de voz, texto e WhatsApp em 7 idiomas BRICS com CEP e GPS automáticos.',
    'pipeline.step2_title': 'Gateway de IA Resiliente',
    'pipeline.step2_desc': 'Extrai domínio e urgência com failover seguro entre Gemini, Groq e NLP Local.',
    'pipeline.step3_title': 'Pontos Críticos Geoespaciais',
    'pipeline.step3_desc': 'Combina dados com buffer de privacidade espacial de 300m.',
    'pipeline.step4_title': 'Recomendações Políticas',
    'pipeline.step4_desc': 'Classifica projetos de alto impacto usando pontuação composta de 6 fatores.',
    'sandbox.badge': 'Ambiente Interativo ao Vivo',
    'sandbox.title': 'Teste Extração de Voz e Intenção de IA',
    'sandbox.subtitle': 'Experimente a estruturação automática da fala em tempo real.',
    'sandbox.full_portal_btn': 'Portal Completo do Cidadão',
    'demands.badge': 'Sinais de Demanda em Tempo Real',
    'demands.title': 'Problemas Comunitários Registrados Recentemente',
    'demands.view_all_btn': 'Ver Todos os Problemas',
    'map.badge': 'Suporte a Decisão Espacial',
    'map.title': 'Mapeamento de Demanda e Déficit Territorial BRICS',
    'map.subtitle': 'Visualização de pontos críticos em todos os países membros.',
    'map.launch_btn': 'Abrir Espaço de Priorização',
    'footer.dpg_header': 'Trilha 1 BRICS — IA para Governança e Infraestrutura',
    'footer.dpg_desc': 'Bem Público Digital de código aberto alinhando voz cidadã a orçamentos públicos.',
    'footer.member_nations': 'IMPLANTAÇÃO PILOTO DOS PAÍSES MEMBROS',
    'footer.product_surfaces': 'Módulos do Produto',
    'footer.privacy_governance': 'Privacidade e Governança',
    'footer.municipal_access': 'Acesso Municipal',
    'footer.official_login': 'Login Oficial de Governança',
  },
  ru: {
    'nav.overview': 'Обзор',
    'nav.citizen': 'Голос Граждан',
    'nav.operations': 'Операционный Центр',
    'nav.planning': 'Аналитика и Политика',
    'nav.impact': 'Реестр Результатов',
    'nav.governance': 'Управление и Этика',
    'nav.sign_in': 'Войти',
    'nav.sign_out': 'Выйти',
    'header.subtitle': 'ИИ для Цифровой Общественной Инфраструктуры и Управления',
    'header.dpg_badge': 'DPG v1.0',
    'hero.track_badge': 'БРИКС Трек 1 — ИИ для Общественной Инфраструктуры',
    'hero.title_part1': 'Связывая Потребности Граждан с',
    'hero.title_highlight': 'Национальными Приоритетами Инфраструктуры',
    'hero.subtitle': 'Масштабируемая многоязычная платформа ИИ, разработанная как Цифровое Общественное Благо — агрегирующая запросы граждан по голосу, тексту и мессенджерам для выявления очагов спроса и оптимизации бюджетных расходов.',
    'hero.search_placeholder': 'Поиск очагов спроса, индексов (420000), воды, клиник...',
    'hero.voice_report_btn': 'Голосовой Отчет',
    'hero.direct_filters': 'Фильтры:',
    'kpi.requests_num': '1 280+',
    'kpi.requests_label': 'ОБРАЩЕНИЙ ГРАЖДАН',
    'kpi.hotspots_num': '48',
    'kpi.hotspots_label': 'ОЧАГОВ СПРОСА',
    'kpi.triage_sla_num': '< 4 Часов',
    'kpi.triage_sla_label': 'МАРШРУТИЗАЦИЯ ИИ',
    'kpi.spending_num': '$3.55M',
    'kpi.spending_label': 'НАПРАВЛЕННЫЕ ИНВЕСТИЦИИ',
    'ticker.verified_deliveries': 'Подтвержденные Проекты',
    'ticker.view_registry': 'Открыть Реестр',
    'pipeline.badge': 'Система Поддержки Решений',
    'pipeline.title': 'От Голоса Жителей до Обоснованных Бюджетов',
    'pipeline.subtitle': 'Интеграция муниципальных систем через прозрачный многофакторный анализ.',
    'pipeline.step1_title': 'Многоязычный Прием',
    'pipeline.step1_desc': 'Прием голосовых и текстовых обращений на 7 языках стран БРИКС с авто-GPS и индексами.',
    'pipeline.step2_title': 'Отказоустойчивый ИИ',
    'pipeline.step2_desc': 'Классификация категорий и срочности с каскадным переключением Gemini, Groq и локального NLP.',
    'pipeline.step3_title': 'Геопространственные Очаги',
    'pipeline.step3_desc': 'Кластеризация с буфером конфиденциальности 300м.',
    'pipeline.step4_title': 'Рекомендации по Развитию',
    'pipeline.step4_desc': 'Ранжирование проектов на основе 6 ключевых факторов.',
    'sandbox.badge': 'Интерактивная Среда',
    'sandbox.title': 'Тестирование Распознавания Голоса и ИИ',
    'sandbox.subtitle': 'Оцените автоматическое структурирование речи в реальном времени.',
    'sandbox.full_portal_btn': 'Портал Подачи Обращений',
    'demands.badge': 'Живой Сигнал Спроса',
    'demands.title': 'Недавно Зарегистрированные Проблемы',
    'demands.view_all_btn': 'Все Проблемы и Подача',
    'map.badge': 'Пространственный Анализ',
    'map.title': 'Карта Очагов Спроса на Территориях БРИКС',
    'map.subtitle': 'Мониторинг инфраструктурных потребностей во всех странах-участницах.',
    'map.launch_btn': 'Открыть Рабочую Зону',
    'footer.dpg_header': 'БРИКС Трек 1 — ИИ для Инфраструктуры и Управления',
    'footer.dpg_desc': 'Цифровое Общественное Благо с открытым исходным кодом.',
    'footer.member_nations': 'ПИЛОТНОЕ РАЗВЕРТЫВАНИЕ В СТРАНАХ-УЧАСТНИЦАХ',
    'footer.product_surfaces': 'Модули Продукта',
    'footer.privacy_governance': 'Конфиденциальность и Управление',
    'footer.municipal_access': 'Муниципальный Доступ',
    'footer.official_login': 'Официальный Вход',
  },
  zh: {
    'nav.overview': '概览',
    'nav.citizen': '市民之声',
    'nav.operations': '运营处置台',
    'nav.planning': '政策智能决策',
    'nav.impact': '基础设施交付登记',
    'nav.governance': '治理与伦理中心',
    'nav.sign_in': '登录',
    'nav.sign_out': '退出',
    'header.subtitle': '面向数字公共基础设施与治理的人工智能',
    'header.dpg_badge': 'DPG v1.0',
    'hero.track_badge': '金砖国家赛道 1 — 数字公共基础设施与治理人工智能',
    'hero.title_part1': '将市民诉求与',
    'hero.title_highlight': '国家基础设施优先事项紧密连接',
    'hero.subtitle': '作为“数字公共产品”构建的可扩展多语言AI平台——聚合跨越金砖各国的语音、文字和消息请求，实时发现需求热点，消除支出错位，并为国家决策者推荐高优先级公共基础设施工程。',
    'hero.search_placeholder': '搜索需求热点、邮编 (610000)、供水、诊所...',
    'hero.voice_report_btn': '语音汇报',
    'hero.direct_filters': '快捷筛选:',
    'kpi.requests_num': '1,280+',
    'kpi.requests_label': '市民诉求总量',
    'kpi.hotspots_num': '48',
    'kpi.hotspots_label': '需求集中热点',
    'kpi.triage_sla_num': '< 4 小时',
    'kpi.triage_sla_label': 'AI分诊与智能派单',
    'kpi.spending_num': '$3.55M',
    'kpi.spending_label': '精准对齐公共投资',
    'ticker.verified_deliveries': '已验证交付项目',
    'ticker.view_registry': '查看项目登记',
    'pipeline.badge': '端到端决策支持系统',
    'pipeline.title': '从民间口述到有据可依的公共预算',
    'pipeline.subtitle': '通过透明的多准则政策智能打通分散的市政系统。',
    'pipeline.step1_title': '多渠道多语言接入',
    'pipeline.step1_desc': '支持7种金砖试点语言的语音、文字、微信机器和USSD输入，附带自动GPS和邮编定位。',
    'pipeline.step2_title': '高韧性AI推理网关',
    'pipeline.step2_desc': '结合Gemini、Groq和本地NLP的多级安全故障切换提取诉求领域与紧急度。',
    'pipeline.step3_title': '地理空间热点聚类',
    'pipeline.step3_desc': '结合300米空间隐私缓冲与国家人口普查指标聚类需求。',
    'pipeline.step4_title': '政策推荐与交付',
    'pipeline.step4_desc': '基于6要素综合加权评分智能推荐并跟踪闭环工程落地。',
    'sandbox.badge': '实时交互沙盒',
    'sandbox.title': '体验多语言语音输入与AI意图提取',
    'sandbox.subtitle': '亲身体验杂乱口语输入如何被实时结构化。',
    'sandbox.full_portal_btn': '打开完整诉求提交门户',
    'demands.badge': '实时需求信号',
    'demands.title': '近期登记的社区基础设施缺陷',
    'demands.view_all_btn': '查看全部并提交诉求',
    'map.badge': '空间智能决策支持',
    'map.title': '金砖国家领土需求热点与赤字地图',
    'map.subtitle': '跨南非、印度、巴西、俄罗斯、中国、埃及和埃塞俄比亚的实时需求可视化。',
    'map.launch_btn': '启动政策智能工作台',
    'footer.dpg_header': '金砖国家赛道 1 — 数字公共基础设施与治理AI',
    'footer.dpg_desc': '开源数字公共产品，连接基层民间声音与国家财政预算。',
    'footer.member_nations': '成员国试点部署覆盖',
    'footer.product_surfaces': '产品功能模块',
    'footer.privacy_governance': '隐私保护与治理规范',
    'footer.municipal_access': '市政专用通道',
    'footer.official_login': '官方治理系统登录',
  },
  ar: {
    'nav.overview': 'نظرة عامة',
    'nav.citizen': 'صوت المواطن',
    'nav.operations': 'مكتب العمليات',
    'nav.planning': 'ذكاء السياسات',
    'nav.impact': 'سجل الأثر',
    'nav.governance': 'الحوكمة والأخلاقيات',
    'nav.sign_in': 'تسجيل الدخول',
    'nav.sign_out': 'تسجيل الخروج',
    'header.subtitle': 'الذكاء الاصطناعي للبنية التحتية العامة الرقمية والحوكمة',
    'header.dpg_badge': 'DPG v1.0',
    'hero.track_badge': 'مسار بريكس 1 — الذكاء الاصطناعي للبنية التحتية العامة الرقمية',
    'hero.title_part1': 'ربط احتياجات المواطنين بـ',
    'hero.title_highlight': 'أولويات البنية التحتية الوطنية',
    'hero.subtitle': 'منصة ذكاء اصطناعي متعددة اللغات صُممت كمنفعة عامة رقمية (DPG) لتجميع طلبات المواطنين عبر الصوت والنص وتحديد بؤر الاحتياج عبر دول بريكس.',
    'hero.search_placeholder': 'ابحث في بؤر الاحتياج، الرمز البريدي، المياه، الصحة...',
    'hero.voice_report_btn': 'تقرير صوتي',
    'hero.direct_filters': 'مرشحات مباشرة:',
    'kpi.requests_num': '1,280+',
    'kpi.requests_label': 'طلبات المواطنين',
    'kpi.hotspots_num': '48',
    'kpi.hotspots_label': 'بؤر الاحتياج',
    'kpi.triage_sla_num': '< 4 ساعات',
    'kpi.triage_sla_label': 'توجيه الذكاء الاصطناعي',
    'kpi.spending_num': '$3.55M',
    'kpi.spending_label': 'الإنفاق الموجّه',
    'ticker.verified_deliveries': 'المشاريع المنفذة',
    'ticker.view_registry': 'عرض السجل',
    'pipeline.badge': 'نظام دعم القرار المتكامل',
    'pipeline.title': 'من صوت المواطن إلى قرارات الميزانية العامة',
    'pipeline.subtitle': 'ربط الأنظمة البلدية المشتتة من خلال ذكاء السياسات متعدد المعايير.',
    'pipeline.step1_title': 'استقبال متعدد اللغات',
    'pipeline.step1_desc': 'التقاط الملاحظات الصوتية والنصوص عبر 7 لغات مع تحديد الموقع التلقائي والرمز البريدي.',
    'pipeline.step2_title': 'بوابة ذكاء اصطناعي مرنة',
    'pipeline.step2_desc': 'تصنيف دقيق مع دعم التبديل التلقائي بين نماذج الذكاء الاصطناعي.',
    'pipeline.step3_title': 'بؤر جغرافية مكانية',
    'pipeline.step3_desc': 'تجميع الطلبات مع حماية الخصوصية المكانية لمسافة 300 متر.',
    'pipeline.step4_title': 'توصيات المشاريع',
    'pipeline.step4_desc': 'ترتيب أولويات الإنفاق بناءً على 6 معايير مركبة.',
    'sandbox.badge': 'بيئة اختبار تفاعلية',
    'sandbox.title': 'اختبر استخراج النوايا بالصوت والذكاء الاصطناعي',
    'sandbox.subtitle': 'جرّب المعالجة التلقائية للهجات المنطوقة في الوقت الفعلي.',
    'sandbox.full_portal_btn': 'فتح بوابة المواطنين الكاملة',
    'demands.badge': 'إشارات الطلب الحية',
    'demands.title': 'مشكلات البنية التحتية المسجلة حديثاً',
    'demands.view_all_btn': 'عرض كل الطلبات وتقديم بلاغ',
    'map.badge': 'دعم القرار المكاني',
    'map.title': 'خريطة بؤر الطلب وفجوات البنية التحتية في بريكس',
    'map.subtitle': 'متابعة الاحتياجات في مصر والإمارات والهند وجنوب أفريقيا وباقي الدول.',
    'map.launch_btn': 'فتح مساحة عمل الأولويات',
    'footer.dpg_header': 'مسار بريكس 1 — الذكاء الاصطناعي للبنية التحتية والحوكمة',
    'footer.dpg_desc': 'منفعة عامة رقمية مفتوحة المصدر لربط صوت المواطنين بالموازنات العامة.',
    'footer.member_nations': 'نطاق الدول الأعضاء',
    'footer.product_surfaces': 'وحدات المنصة',
    'footer.privacy_governance': 'الخصوصية والحوكمة',
    'footer.municipal_access': 'دخول الجهات البلدية',
    'footer.official_login': 'تسجيل الدخول الرسمي',
  },
  sw: {
    'nav.overview': 'Muhtasari',
    'nav.citizen': 'Sauti ya Raia',
    'nav.operations': 'Dawati la Uendeshaji',
    'nav.planning': 'Akili ya Sera',
    'nav.impact': 'Sajili ya Matokeo',
    'nav.governance': 'Utawala na Maadili',
    'nav.sign_in': 'Ingia',
    'nav.sign_out': 'Toka',
    'header.subtitle': 'AI kwa Miundombinu ya Dijitali na Utawala',
    'header.dpg_badge': 'DPG v1.0',
    'hero.track_badge': 'Wimbo wa 1 wa BRICS — AI kwa Miundombinu ya Umma',
    'hero.title_part1': 'Kuunganisha Mahitaji ya Raia na',
    'hero.title_highlight': 'Vipaumbele vya Miundombinu ya Kitaifa',
    'hero.subtitle': 'Jukwaa la AI la lugha nyingi lililoundwa kama Bidhaa ya Umma ya Kidijitali (DPG) — kukusanya maombi ya maendeleo ya raia kupitia sauti, maandishi, na ujumbe ili kuweka wazi maeneo yenye uhitaji mkubwa.',
    'hero.search_placeholder': 'Tafuta maeneo ya uhitaji, msimbo wa posta, maji, zahanati...',
    'hero.voice_report_btn': 'Ripoti kwa Sauti',
    'hero.direct_filters': 'Vichungi vya Haraka:',
    'kpi.requests_num': '1,280+',
    'kpi.requests_label': 'MAOMBI YA RAIA',
    'kpi.hotspots_num': '48',
    'kpi.hotspots_label': 'MAENEO YA UHITAJI',
    'kpi.triage_sla_num': '< Saa 4',
    'kpi.triage_sla_label': 'UCHAMBUZI WA AI',
    'kpi.spending_num': '$3.55M',
    'kpi.spending_label': 'MATUMIZI YALIYOLENGWA',
    'ticker.verified_deliveries': 'Miradi Iliyokamilika',
    'ticker.view_registry': 'Tazama Sajili',
    'pipeline.badge': 'Mfumo wa Usaidizi wa Maamuzi',
    'pipeline.title': 'Kutoka Sauti ya Raia Hadi Bajeti Halisi ya Umma',
    'pipeline.subtitle': 'Kuunganisha mifumo iliyotawanyika kupitia akili ya sera ya wazi.',
    'pipeline.step1_title': 'Mapokezi ya Lugha Nyingi',
    'pipeline.step1_desc': 'Inanasa sauti na maandishi katika lugha 7 za BRICS zenye GPS ya kiotomatiki.',
    'pipeline.step2_title': 'Njia Imara ya AI',
    'pipeline.step2_desc': 'Uchambuzi thabiti wa kiwango cha dharura na idadi ya watu walioathirika.',
    'pipeline.step3_title': 'Maeneo ya Kijiografia',
    'pipeline.step3_desc': 'Ukaguzi wa data na ulinzi wa faragha wa mita 300.',
    'pipeline.step4_title': 'Mapendekezo ya Sera',
    'pipeline.step4_desc': 'Kupanga miradi ya kipaumbele kulingana na vigezo 6 muhimu.',
    'sandbox.badge': 'Uwanja wa Majaribio wa Moja kwa Moja',
    'sandbox.title': 'Jaribu Unasaji wa Sauti na Akili ya AI',
    'sandbox.subtitle': 'Ona jinsi mazungumzo yanavyopangwa kiotomatiki kwa wakati halisi.',
    'sandbox.full_portal_btn': 'Fungua Lango Kamili la Raia',
    'demands.badge': 'Mwangwi wa Moja kwa Moja',
    'demands.title': 'Changamoto za Miundombinu Zilizoripotiwa Hivi Karibuni',
    'demands.view_all_btn': 'Tazama Zote na Uwasilishe Yako',
    'map.badge': 'Usaidizi wa Maamuzi ya Maeneo',
    'map.title': 'Ramani ya Mahitaji na Mapungufu ya BRICS',
    'map.subtitle': 'Ukaguzi wa kina wa miundombinu kote barani Afrika na nchi wanachama.',
    'map.launch_btn': 'Fungua Eneo la Kazi la Sera',
    'footer.dpg_header': 'BRICS Wimbo wa 1 — AI kwa Miundombinu na Utawala',
    'footer.dpg_desc': 'Bidhaa ya Umma ya Kidijitali inayounganisha sauti ya jamii na bajeti za serikali.',
    'footer.member_nations': 'USAMBAZAJI WA MAJARIBIO KATIKA NCHI WANACHAMA',
    'footer.product_surfaces': 'Sehemu za Mfumo',
    'footer.privacy_governance': 'Faragha na Utawala',
    'footer.municipal_access': 'Ufikiaji wa Manispaa',
    'footer.official_login': 'Kuingia Rasmi kwa Serikali',
  }
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<SupportedLanguage>('en');

  useEffect(() => {
    const saved = localStorage.getItem('civicpulse_language');
    if (saved && ['en', 'hi', 'pt', 'ru', 'zh', 'ar', 'sw'].includes(saved)) {
      setLanguageState(saved as SupportedLanguage);
    }
  }, []);

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    localStorage.setItem('civicpulse_language', lang);
  };

  const t = (key: string): string => {
    const langDict = TRANSLATIONS[language] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
